version: "3.7"
services:
    nginx:
        image: nginx:1.25-alpine
        ports:
            - 8020:80
        volumes:
            - ./:/var/www/html
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - postgres
    postgres:
        image: postgres:15.2-alpine
        ports:
            - 5434:5432
        volumes:
          - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: password
            POSTGRES_DB: laravel
    redis:
        image: redis:7.0-bullseye
        ports:
            - 6381:6379
        command: redis-server --appendonly yes
    mail:
        image: mailhog/mailhog:v1.0.1
        ports:
            - 8027:8025

volumes:
  postgres:
